In [1]:
import pandas as pd
import os

# Import Datasets
Dataset 
> Link: https://www.kaggle.com/datasets/arashnic/book-recommendation-dataset

In [2]:
# file_path = os.path.abspath('./datasets/Books.csv')
books = pd.read_csv('../datasets/Books.csv')

display(books.head())

C:\Users\Syah\AppData\Local\Temp\ipykernel_5812\3755506606.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('../datasets/Books.csv')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [3]:
display(books.head())

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

# Shape of Data

In [4]:
books.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

Membetulkan data NaN yang ada pada kolom Book-Author

In [5]:
books[books['Book-Author'].isna()]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
187689,9627982032,The Credit Suisse Guide to Managing Your Perso...,NaN,1995,Edinburgh Financial Publishing,http://images.amazon.com/images/P/9627982032.0...,http://images.amazon.com/images/P/9627982032.0...,http://images.amazon.com/images/P/9627982032.0...

In [6]:
books.iloc[187689]['Book-Title']

'The Credit Suisse Guide to Managing Your Personal Wealth'

Setelah mencari manual, kami mendapatkan nama author pada buku ini:<br>
***Downes, Larissa Anne***

In [7]:
books.iloc[187689]['Book-Author'] = 'Downes, Larissa Anne'

In [8]:
books.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

Pada Kolom Publisher masih terdapat dua value NaN

In [9]:
books[books['Publisher'].isna()]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
128890,193169656X,Tyrant Moon,Elaine Corvidae,2002,NaN,http://images.amazon.com/images/P/193169656X.0...,http://images.amazon.com/images/P/193169656X.0...,http://images.amazon.com/images/P/193169656X.0...
129037,1931696993,Finders Keepers,Linnea Sinclair,2001,NaN,http://images.amazon.com/images/P/1931696993.0...,http://images.amazon.com/images/P/1931696993.0...,http://images.amazon.com/images/P/1931696993.0...

In [10]:
books.iloc[128890]['Publisher'] = 'NovelBooks'
books.iloc[129037]['Publisher'] = 'NovelBooks'

In [11]:
books.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [12]:
books.duplicated().sum()

0

In [13]:
# initialize data of lists.
data = {'idPerpus': ['173', '213', '913', ],
        'Perpustakaan': ['Perpustakaan Kota Bandung', 'Perpustakaan ITB', 'Perpustakaan UPI'],
        'Alamat':['Jl. Seram No.2, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat 40115', 'Kawasan ITB Kampus Ganesa, Jl. Ganesa No.10, Lb. Siliwangi, Kecamatan Coblong, Kota Bandung, Jawa Barat 40132', ' Jl. Dr. Setiabudi No.229, Isola, Kec. Sukasari, Kota Bandung, Jawa Barat 40154'],
        'Lon':['107.6137978229117','107.6107340527733','107.59142271780094'],
        'Lat':['-6.908202787856465','-6.888200572853506','-6.860911863002797']
        }
# Create DataFrame
perpus_df = pd.DataFrame(data)
 
# Print the output.
print(perpus_df)

  idPerpus               Perpustakaan  \
0      173  Perpustakaan Kota Bandung
1      213           Perpustakaan ITB
2      913           Perpustakaan UPI

                                              Alamat                 Lon  \
0  Jl. Seram No.2, Citarum, Kec. Bandung Wetan, K...   107.6137978229117
1  Kawasan ITB Kampus Ganesa, Jl. Ganesa No.10, L...   107.6107340527733
2   Jl. Dr. Setiabudi No.229, Isola, Kec. Sukasar...  107.59142271780094

                  Lat
0  -6.908202787856465
1  -6.888200572853506
2  -6.860911863002797

In [14]:
perpus_df

,idPerpus,Perpustakaan,Alamat,Lon,Lat
0,173,Perpustakaan Kota Bandung,"Jl. Seram No.2, Citarum, Kec. Bandung Wetan, K...",107.6137978229117,-6.908202787856465
1,213,Perpustakaan ITB,"Kawasan ITB Kampus Ganesa, Jl. Ganesa No.10, L...",107.6107340527733,-6.888200572853506
2,913,Perpustakaan UPI,"Jl. Dr. Setiabudi No.229, Isola, Kec. Sukasar...",107.59142271780094,-6.860911863002797

In [15]:
import random
id_perpus_values = (list(perpus_df['idPerpus']) * (len(books) // len(perpus_df) + 1))[:len(books)]
random.shuffle(id_perpus_values)

books['idPerpus'] = id_perpus_values

In [16]:
display(books)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,idPerpus
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,213
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,913
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,913
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,213
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,213
...,...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,173
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,213
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,213
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,213
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,913

In [17]:
columns_to_drop = ['Image-URL-S', 'Image-URL-L', 'Image-URL-M']
books = books.drop(columns=columns_to_drop, axis=1)

In [18]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,idPerpus
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,213
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,913
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,913
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,213
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,213

In [21]:
books.to_csv('../datasets/CleanDataBook.csv',index=False)
perpus_df.to_csv('../datasets/Perpustakaan.csv',index=False)